/* UPDATE */
CREATE TABLE DEPT_TMP AS SELECT * FROM DEPT d;

SELECT * 
  FROM DEPT_TMP;

-- UPDATE ~ SET
UPDATE DEPT_TMP 
   SET LOC = 'SEOUL';		-- 해당열 전체 수정
   
UPDATE DEPT_TMP
   SET DNAME = 'DATABASE'
 WHERE DEPTNO = 40;

UPDATE DEPT_TMP
   SET LOC = 'BUSAN'
 WHERE DEPTNO = 40;
 
-- 서브쿼리를 사용한 데이터 수정
UPDATE DEPT_TMP
   SET (DNAME, LOC) = (SELECT DNAME, LOC
   		  				 FROM DEPT
   		 				WHERE DEPTNO = 40)
 WHERE DEPTNO = 40;

/* DELETE */
CREATE TABLE EMP_TMP AS SELECT * FROM EMP;

SELECT *
  FROM EMP_TMP;
  
DELETE FROM EMP_TMP
 WHERE JOB = 'SALESMAN';
 
DELETE FROM EMP_TMP;	-- 데이터만 삭제되고 테이블은 삭제되지 않음

SELECT * 
  FROM EMP_TMP;

DROP TABLE EMP_TMP;		-- 테이블 삭제(DROP TABLE [테이블 이름])


/* 트랜젝션 */
-- 트랜젝션: 하나의 명령을 실행하는 단위
-- 테이블 수정 중에 다른 사람 접근 불가
-- 어떤 하나의 행위가 반영될 때까지를 하나의 트랜젝션이라 함
CREATE TABLE DEPT_TMP;

SELECT * 
  FROM TAB;		-- 전체 테이블 조회

SELECT * 
  FROM DEPT_TMP;
  
CREATE TABLE DEPT_TCL
	AS SELECT * FROM DEPT d;

SELECT *
  FROM DEPT_TCL;
  
INSERT INTO DEPT_TCL 
VALUES (50, 'DATABASE', 'BUSAN');

UPDATE DEPT_TCL
   SET LOC = 'BUSAN'
 WHERE DEPTNO = 40;
 
DELETE FROM DEPT_TCL
 WHERE DNAME = 'RESEARCH'
 
ROLLBACK;		-- 트랜젝션 취소
COMMIT;			-- 트랜젝션 반영


/* 섹션 */
-- 로그인한 사용자가 로그아웃할 때까지

/* VIEW */
-- 하나 이상의 SELECT문을 가지고 있는 하나의 객체
-- 서브쿼리로 대체 가능
-- 보안성, 편리성
CREATE VIEW VM_EMP
    AS (SELECT EMPNO, ENAME, JOB, DEPTNO
          FROM EMP e
         WHERE DEPTNO = 20);
    
SELECT * 
  FROM VM_EMP;
  
SELECT *
  FROM USER_VIEWS;
  
DROP VIEW VM_EMP;

-- 테이블, 데이터 사전, 인덱스, 뷰, 시퀀스, 동의어

/* 데이터 사전 */
-- 데이터 사전: 테이블 관련 메타 정보 저장되어 있음
SELECT *
  FROM DICT;	-- 사용 가능한 데이터 사전
  
SELECT TABLE_NAME
  FROM USER_TABLES; 		-- 현재 접속 사용자(ADAM)이 가지고 있는 테이블 조회
  
SELECT OWNER, TABLE_NAME
  FROM ALL_TABLES;			-- 현재 계정이 접속 가능한 모든 테이블 조회
  
SELECT *
  FROM DBA_TABLES;			-- 관리 권한의 사용자만 접근 가능
  
/* 시퀀스 */
CREATE TABLE DEPT_SEQ
  AS SELECT *
       FROM DEPT d
      WHERE 1 <> 1;		-- <>: 부등호 / 빈테이블(컬럼만 같은) 만들어짐
       
SELECT *
  FROM DEPT_SEQ;
  
DROP TABLE DEPT_SEQ;

CREATE SEQUENCE SEQ_DEPT_SEQUENCE	-- 시퀀스 테이블 이름
INCREMENT BY 10						-- 10씩 증가
 START WITH 10						-- 시작값
MAXVALUE 90							-- 최대값
MINVALUE 0							-- 최소값
NOCYCLE								-- 순환안함(최대값이면 정지)
CACHE 2;							-- 2개의 CACHE 사용

SELECT *
  FROM USER_SEQUENCES;
  
 
-- 시퀀스 이름.NEXTVAL
INSERT INTO DEPT_SEQ(DEPTNO, DNAME, LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'BUSAN');

SELECT *
  FROM DEPT_SEQ
 ORDER BY DEPTNO;
 
INSERT INTO DEPT_SEQ(DEPTNO, DNAME, LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE1', 'SEOUL');

SELECT *
  FROM DEPT_SEQ
 ORDER BY DEPTNO;
 
INSERT INTO DEPT_SEQ(DEPTNO, DNAME, LOC)
VALUES (SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE2', 'SEOUL');

-- 시퀀스 이름.CURRVAL: 가장 마지막 시퀀스 확인
SELECT SEQ_DEPT_SEQUENCE.CURRVAL
  FROM DUAL;
  
-- 시퀀스 수정
ALTER SEQUENCE SEQ_DEPT_SEQUENCE
INCREMENT BY 3
MAXVALUE 99
CYCLE;

SELECT *
  FROM USER_SEQUENCES;
  
DROP SEQUENCE SEQ_DEPT_SEQUENCE;

COMMIT;